<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\DBAL\Platforms\SQLitePlatform;
use Doctrine\Migrations\AbstractMigration;

final class Version20260517024500 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add billing plan fields and notification email quota logs.';
    }

    public function up(Schema $schema): void
    {
        if ($this->connection->getDatabasePlatform() instanceof SQLitePlatform) {
            $this->addSql("ALTER TABLE app_user ADD COLUMN plan VARCHAR(255) DEFAULT 'free' NOT NULL");
            $this->addSql('ALTER TABLE app_user ADD COLUMN stripe_customer_id VARCHAR(255) DEFAULT NULL');
            $this->addSql('ALTER TABLE app_user ADD COLUMN stripe_subscription_id VARCHAR(255) DEFAULT NULL');
            $this->addSql('ALTER TABLE app_user ADD COLUMN stripe_subscription_status VARCHAR(64) DEFAULT NULL');
            $this->addSql('ALTER TABLE app_user ADD COLUMN stripe_current_period_end DATETIME DEFAULT NULL');
            $this->addSql('CREATE TABLE notification_email_log (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, user_id INTEGER NOT NULL, project_id INTEGER DEFAULT NULL, type VARCHAR(32) NOT NULL, email VARCHAR(180) NOT NULL, sent_at DATETIME NOT NULL, CONSTRAINT FK_7D20ED25A76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_7D20ED25166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE)');
            $this->addSql('CREATE INDEX IDX_7D20ED25A76ED395 ON notification_email_log (user_id)');
            $this->addSql('CREATE INDEX IDX_7D20ED25166D1F9C ON notification_email_log (project_id)');
            $this->addSql('CREATE INDEX IDX_NOTIFICATION_EMAIL_LOG_SENT_AT ON notification_email_log (sent_at)');

            return;
        }

        $this->addSql("ALTER TABLE app_user ADD plan VARCHAR(255) DEFAULT 'free' NOT NULL");
        $this->addSql('ALTER TABLE app_user ADD stripe_customer_id VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE app_user ADD stripe_subscription_id VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE app_user ADD stripe_subscription_status VARCHAR(64) DEFAULT NULL');
        $this->addSql('ALTER TABLE app_user ADD stripe_current_period_end TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('CREATE TABLE notification_email_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, project_id INT DEFAULT NULL, type VARCHAR(32) NOT NULL, email VARCHAR(180) NOT NULL, sent_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_7D20ED25A76ED395 ON notification_email_log (user_id)');
        $this->addSql('CREATE INDEX IDX_7D20ED25166D1F9C ON notification_email_log (project_id)');
        $this->addSql('CREATE INDEX IDX_NOTIFICATION_EMAIL_LOG_SENT_AT ON notification_email_log (sent_at)');
        $this->addSql('ALTER TABLE notification_email_log ADD CONSTRAINT FK_7D20ED25A76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE notification_email_log ADD CONSTRAINT FK_7D20ED25166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        if ($this->connection->getDatabasePlatform() instanceof SQLitePlatform) {
            $this->addSql('DROP TABLE notification_email_log');
            $this->addSql('ALTER TABLE app_user DROP COLUMN plan');
            $this->addSql('ALTER TABLE app_user DROP COLUMN stripe_customer_id');
            $this->addSql('ALTER TABLE app_user DROP COLUMN stripe_subscription_id');
            $this->addSql('ALTER TABLE app_user DROP COLUMN stripe_subscription_status');
            $this->addSql('ALTER TABLE app_user DROP COLUMN stripe_current_period_end');

            return;
        }

        $this->addSql('ALTER TABLE notification_email_log DROP CONSTRAINT FK_7D20ED25A76ED395');
        $this->addSql('ALTER TABLE notification_email_log DROP CONSTRAINT FK_7D20ED25166D1F9C');
        $this->addSql('DROP TABLE notification_email_log');
        $this->addSql('ALTER TABLE app_user DROP plan');
        $this->addSql('ALTER TABLE app_user DROP stripe_customer_id');
        $this->addSql('ALTER TABLE app_user DROP stripe_subscription_id');
        $this->addSql('ALTER TABLE app_user DROP stripe_subscription_status');
        $this->addSql('ALTER TABLE app_user DROP stripe_current_period_end');
    }
}
