<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\DBAL\Platforms\SQLitePlatform;
use Doctrine\Migrations\AbstractMigration;

final class Version20260517013000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create NotifyDB MVP tables and Doctrine Messenger transport table.';
    }

    public function up(Schema $schema): void
    {
        if ($this->connection->getDatabasePlatform() instanceof SQLitePlatform) {
            $this->addSql('CREATE TABLE change_event (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, table_name VARCHAR(120) NOT NULL, record_id VARCHAR(120) NOT NULL, event_type VARCHAR(255) NOT NULL, old_values CLOB NOT NULL, new_values CLOB NOT NULL, human_summary CLOB DEFAULT NULL, emailed_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, project_id INTEGER NOT NULL, CONSTRAINT FK_677EB7EA166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
            $this->addSql('CREATE INDEX IDX_677EB7EA166D1F9C ON change_event (project_id)');
            $this->addSql('CREATE INDEX IDX_CHANGE_EVENT_EMAILED_AT ON change_event (emailed_at)');
            $this->addSql('CREATE INDEX IDX_CHANGE_EVENT_CREATED_AT ON change_event (created_at)');
            $this->addSql('CREATE TABLE project (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, name VARCHAR(160) NOT NULL, api_token_hash VARCHAR(64) NOT NULL, api_token_prefix VARCHAR(16) NOT NULL, notification_frequency VARCHAR(255) NOT NULL, ai_summaries_enabled BOOLEAN NOT NULL, notification_email VARCHAR(180) DEFAULT NULL, created_at DATETIME NOT NULL, owner_id INTEGER NOT NULL, CONSTRAINT FK_2FB3D0EE7E3C61F9 FOREIGN KEY (owner_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
            $this->addSql('CREATE UNIQUE INDEX UNIQ_2FB3D0EE74162BCB ON project (api_token_hash)');
            $this->addSql('CREATE INDEX IDX_2FB3D0EE7E3C61F9 ON project (owner_id)');
            $this->addSql('CREATE TABLE app_user (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, email VARCHAR(180) NOT NULL, roles CLOB NOT NULL, password VARCHAR(255) NOT NULL)');
            $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON app_user (email)');
            $this->addSql('CREATE TABLE messenger_messages (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, body CLOB NOT NULL, headers CLOB NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at DATETIME NOT NULL, available_at DATETIME NOT NULL, delivered_at DATETIME DEFAULT NULL)');
            $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');

            return;
        }

        $this->addSql('CREATE TABLE app_user (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON app_user (email)');
        $this->addSql('CREATE TABLE project (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, owner_id INT NOT NULL, name VARCHAR(160) NOT NULL, api_token_hash VARCHAR(64) NOT NULL, api_token_prefix VARCHAR(16) NOT NULL, notification_frequency VARCHAR(255) NOT NULL, ai_summaries_enabled BOOLEAN NOT NULL, notification_email VARCHAR(180) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2FB3D0EE48664869 ON project (api_token_hash)');
        $this->addSql('CREATE INDEX IDX_2FB3D0EE7E3C61F9 ON project (owner_id)');
        $this->addSql('CREATE TABLE change_event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, project_id INT NOT NULL, table_name VARCHAR(120) NOT NULL, record_id VARCHAR(120) NOT NULL, event_type VARCHAR(255) NOT NULL, old_values JSON NOT NULL, new_values JSON NOT NULL, human_summary TEXT DEFAULT NULL, emailed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_CHANGE_EVENT_EMAILED_AT ON change_event (emailed_at)');
        $this->addSql('CREATE INDEX IDX_CHANGE_EVENT_CREATED_AT ON change_event (created_at)');
        $this->addSql('CREATE INDEX IDX_8E7C7D51166D1F9C ON change_event (project_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGSERIAL NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql('ALTER TABLE project ADD CONSTRAINT FK_2FB3D0EE7E3C61F9 FOREIGN KEY (owner_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE change_event ADD CONSTRAINT FK_8E7C7D51166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        if ($this->connection->getDatabasePlatform() instanceof SQLitePlatform) {
            $this->addSql('DROP TABLE messenger_messages');
            $this->addSql('DROP TABLE change_event');
            $this->addSql('DROP TABLE project');
            $this->addSql('DROP TABLE app_user');

            return;
        }

        $this->addSql('ALTER TABLE change_event DROP CONSTRAINT FK_8E7C7D51166D1F9C');
        $this->addSql('ALTER TABLE project DROP CONSTRAINT FK_2FB3D0EE7E3C61F9');
        $this->addSql('DROP TABLE messenger_messages');
        $this->addSql('DROP TABLE change_event');
        $this->addSql('DROP TABLE project');
        $this->addSql('DROP TABLE app_user');
    }
}
